packageExtensions:
  "@firebase/auth@*":
    dependencies:
      "@firebase/app-types": 0.x
      "@firebase/util": 0.x
  "@firebase/database@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": 0.x
  "@firebase/firestore@*":
    dependencies:
      google-auth-library: 5.x
  gatsby-plugin-styled-components@*:
    dependencies:
      babel-plugin-styled-components: 1.x
  gatsby-plugin-typescript@*:
    dependencies:
      gatsby: ^2.0.0
  gatsby@*:
    dependencies:
      "@babel/types": 7.x
      babel-plugin-styled-components: 1.x
      react-refresh: 0.8.x
      styled-components: "*"

yarnPath: .yarn/releases/yarn-1.23.0-20200615.1917.cjs
