export const initial = {
  id: null,
  nr: null,
  vorname: null,
  name: null,
  adresszusatz: null,
  strasse: null,
  plz: null,
  ort: null,
  telefon_privat: null,
  telefon_geschaeft: null,
  telefon_mobile: null,
  email: null,
  kein_email: null,
  bemerkungen: null,
  account_id: null,
  user_role_id: null,
  kommerziell: null,
  info: null,
  aktiv: true,
  _deleted: false,
}

export const empty = {
  id: null,
  nr: null,
  vorname: null,
  name: null,
  adresszusatz: null,
  strasse: null,
  plz: null,
  ort: null,
  telefon_privat: null,
  telefon_geschaeft: null,
  telefon_mobile: null,
  email: null,
  kein_email: null,
  bemerkungen: null,
  account_id: null,
  user_role_id: null,
  kommerziell: null,
  info: null,
  aktiv: true,
  _deleted: false,
}

export const simpleTypes = {
  id: 'uuid',
  nr: 'string',
  vorname: 'string',
  name: 'string',
  adresszusatz: 'string',
  strasse: 'string',
  plz: 'number',
  ort: 'string',
  telefon_privat: 'string',
  telefon_geschaeft: 'string',
  telefon_mobile: 'string',
  email: 'string',
  kein_email: 'boolean',
  bemerkungen: 'string',
  account_id: 'string',
  user_role_id: 'uuid',
  kommerziell: 'boolean',
  info: 'boolean',
  aktiv: 'boolean',
  _deleted: 'boolean',
}
