export const initial = {
  id: null,
  art_id: null,
  person_id: null,
  von_sammlung_id: null,
  von_kultur_id: null,
  datum: null,
  nach_kultur_id: null,
  nach_ausgepflanzt: null,
  von_anzahl_individuen: null,
  anzahl_pflanzen: null,
  anzahl_auspflanzbereit: null,
  gramm_samen: null,
  andere_menge: null,
  geplant: null,
  bemerkungen: null,
  _deleted: false,
}

export const empty = {
  id: null,
  art_id: null,
  person_id: null,
  von_sammlung_id: null,
  von_kultur_id: null,
  datum: null,
  nach_kultur_id: null,
  nach_ausgepflanzt: null,
  von_anzahl_individuen: null,
  anzahl_pflanzen: null,
  anzahl_auspflanzbereit: null,
  gramm_samen: null,
  andere_menge: null,
  geplant: null,
  bemerkungen: null,
  _deleted: false,
}

export const simpleTypes = {
  id: 'uuid',
  art_id: 'uuid',
  person_id: 'uuid',
  von_sammlung_id: 'uuid',
  von_kultur_id: 'uuid',
  datum: 'date',
  nach_kultur_id: 'uuid',
  nach_ausgepflanzt: 'boolean',
  von_anzahl_individuen: 'number',
  anzahl_pflanzen: 'number',
  anzahl_auspflanzbereit: 'number',
  gramm_samen: 'number',
  andere_menge: 'string',
  geplant: 'boolean',
  bemerkungen: 'string',
  _deleted: 'boolean',
}
