const initializeSubscriptions = ({ store }) => ({
  ae_art: store.subscribeAe_art(),
  art: store.subscribeArt(),
  art_file: store.subscribeArt_file(),
  art_qk: store.subscribeArt_qk(),
  art_qk_choosen: store.subscribeArt_qk_choosen(),
  av: store.subscribeAv(),
  event: store.subscribeEvent(),
  garten: store.subscribeGarten(),
  garten_file: store.subscribeGarten_file(),
  gv: store.subscribeGv(),
  herkunft: store.subscribeHerkunft(),
  herkunft_file: store.subscribeHerkunft_file(),
  kultur: store.subscribeKultur(),
  kultur_file: store.subscribeKultur_file(),
  kultur_option: store.subscribeKultur_option(),
  kultur_qk: store.subscribeKultur_qk(),
  kultur_qk_choosen: store.subscribeKultur_qk_choosen(),
  lieferung: store.subscribeLieferung(),
  lieferung_file: store.subscribeLieferung_file(),
  person: store.subscribePerson(),
  person_file: store.subscribePerson_file(),
  person_option: store.subscribePerson_option(),
  sammel_lieferung: store.subscribeSammel_lieferung(),
  sammlung: store.subscribeSammlung(),
  sammlung_file: store.subscribeSammlung_file(),
  teilkultur: store.subscribeTeilkultur(),
  teilzaehlung: store.subscribeTeilzaehlung(),
  user_role: store.subscribeUser_role(),
  zaehlung: store.subscribeZaehlung(),
})

export default initializeSubscriptions
