/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
import { types } from "mobx-state-tree"



/**
* garten_teilzaehlung_sums_select_column
*/
export const garten_teilzaehlung_sums_select_columnEnumType = types.enumeration("garten_teilzaehlung_sums_select_column", [
        "garten_aktiv",
  "garten_anzahl_kulturen",
  "garten_bemerkungen",
  "garten_id",
  "garten_name",
  "garten_ort",
  "garten_person_id",
  "garten_person_name",
  "garten_plz",
  "garten_strasse",
  "id",
  "kultur_aktiv",
  "kultur_anzahl_auspflanzbereit",
  "kultur_anzahl_mutterpflanzen",
  "kultur_anzahl_pflanzen",
  "kultur_art_id",
  "kultur_art_name",
  "kultur_bemerkungen",
  "kultur_erhaltungskultur",
  "kultur_events_anzahl",
  "kultur_events_datum_beschreibung",
  "kultur_herkunft_nr",
  "kultur_id",
  "kultur_letzter_event_beschreibung",
  "kultur_letzter_event_datum",
  "kultur_letzter_event_geplant",
  "kultur_letzter_event_id",
  "kultur_letzter_event_person_name",
  "kultur_letzter_event_teilkultur_bemerkungen",
  "kultur_letzter_event_teilkultur_name",
  "kultur_letzter_event_teilkultur_ort1",
  "kultur_letzter_event_teilkultur_ort2",
  "kultur_letzter_event_teilkultur_ort3",
  "kultur_teilkulturen_anzahl",
  "kultur_teilkulturen_namen",
  "kultur_von_anzahl_individuen",
  "kultur_zaehlungen_anzahl",
  "kultur_zwischenlager",
  "teilzaehlung_andere_menge",
  "teilzaehlung_anzahl_auspflanzbereit",
  "teilzaehlung_anzahl_mutterpflanzen",
  "teilzaehlung_anzahl_pflanzen",
  "teilzaehlung_auspflanzbereit_beschreibung",
  "teilzaehlung_bemerkungen",
  "teilzaehlung_id",
  "teilzaehlung_teilkultur_bemerkungen",
  "teilzaehlung_teilkultur_name",
  "teilzaehlung_teilkultur_ort1",
  "teilzaehlung_teilkultur_ort2",
  "teilzaehlung_teilkultur_ort3",
  "zaehlung_anzahl_auspflanzbereit",
  "zaehlung_anzahl_mutterpflanzen",
  "zaehlung_anzahl_pflanzen",
  "zaehlung_anzahl_teilzaehlungen",
  "zaehlung_bemerkungen",
  "zaehlung_datum",
  "zaehlung_id",
  "zaehlung_prognose",
      ])
