import memoizeOne from 'memoize-one'

import sort from '../sort'
import allParentNodesAreOpen from '../allParentNodesAreOpen'

import buildZaehlungZaehlung from './zaehlung'

export default ({ store }) => {
  const {
    artFolder,
    art,
    artSammlungFolder,
    artSammlung,
    artSammlungAusLieferungFolder,
    artSammlungAusLieferung,
    artKulturFolder,
    artKultur,
    artKulturEventFolder,
    artKulturEvent,
    artKulturAusLieferungFolder,
    artKulturAusLieferung,
    artKulturAnLieferungFolder,
    artKulturAnLieferung,
    artKulturTeilkulturFolder,
    artKulturTeilkultur,
    artKulturZaehlungFolder,
    artKulturZaehlung,
    eventFolder,
    event,
    gartenFolder,
    garten,
    gartenKulturEventFolder,
    gartenKulturEvent,
    gartenKulturFolder,
    gartenKultur,
    gartenKulturAnLieferungFolder,
    gartenKulturAnLieferung,
    gartenKulturAusLieferungFolder,
    gartenKulturAusLieferung,
    gartenKulturTeilkulturFolder,
    gartenKulturTeilkultur,
    gartenKulturZaehlungFolder,
    gartenKulturZaehlung,
    herkunftFolder,
    herkunft,
    herkunftSammlungFolder,
    herkunftSammlung,
    herkunftSammlungAusLieferungFolder,
    herkunftSammlungausLieferung,
    kulturFolder,
    kultur,
    kulturEventFolder,
    kulturEvent,
    kulturAnLieferungFolder,
    kulturLieferungAnLieferung,
    kulturAusLieferungFolder,
    kulturLieferungAusLieferung,
    kulturTeilkulturFolder,
    kulturTeilkultur,
    kulturZaehlungFolder,
    kulturZaehlung,
    lieferungFolder,
    lieferung,
    personFolder,
    person,
    personGartenFolder,
    personLieferungFolder,
    personGarten,
    personGartenKulturFolder,
    personGartenKultur,
    personGartenKulturEventFolder,
    personGartenKulturEvent,
    personGartenKulturAnlieferungFolder,
    personGartenKulturAnlieferung,
    personGartenKulturAuslieferungFolder,
    personGartenKulturAuslieferung,
    personGartenKulturTeilkulturFolder,
    personGartenKulturTeilkultur,
    personGartenKulturZaehlungFolder,
    personGartenKulturZaehlung,
    personLieferung,
    personSammlungFolder,
    personSammlungSammlung,
    sammelLieferungFolder,
    sammelLieferung,
    sammelLieferungLieferungFolder,
    sammelLieferungLieferung,
    sammlungFolder,
    teilkulturFolder,
    teilkultur,
    zaehlungFolder,
  } = store.tree
  const openNodes = store.tree.openNodes.sort(sort)

  let nodes = [
    ...artFolder,
    ...art,
    ...artSammlungFolder,
    ...artSammlung,
    ...artSammlungAusLieferungFolder,
    ...artSammlungAusLieferung,
    ...artKulturFolder,
    ...artKulturZaehlungFolder,
    ...artKulturZaehlung,
    ...artKultur,
    ...artKulturEventFolder,
    ...artKulturEvent,
    ...artKulturAusLieferungFolder,
    ...artKulturAusLieferung,
    ...artKulturAnLieferungFolder,
    ...artKulturAnLieferung,
    ...artKulturTeilkulturFolder,
    ...artKulturTeilkultur,
    ...gartenFolder,
    ...garten,
    ...gartenKulturEventFolder,
    ...gartenKulturEvent,
    ...gartenKulturFolder,
    ...gartenKultur,
    ...gartenKulturAnLieferungFolder,
    ...gartenKulturAnLieferung,
    ...gartenKulturAusLieferungFolder,
    ...gartenKulturAusLieferung,
    ...gartenKulturTeilkulturFolder,
    ...gartenKulturTeilkultur,
    ...gartenKulturZaehlungFolder,
    ...gartenKulturZaehlung,
    ...herkunftFolder,
    ...herkunft,
    ...herkunftSammlungFolder,
    ...herkunftSammlung,
    ...herkunftSammlungAusLieferungFolder,
    ...herkunftSammlungausLieferung,
    ...kulturFolder,
    ...kultur,
    ...kulturEventFolder,
    ...kulturEvent,
    ...kulturAnLieferungFolder,
    ...kulturLieferungAnLieferung,
    ...kulturAusLieferungFolder,
    ...kulturLieferungAusLieferung,
    ...kulturTeilkulturFolder,
    ...kulturTeilkultur,
    ...kulturZaehlungFolder,
    ...kulturZaehlung,
    ...lieferungFolder,
    ...lieferung,
    ...eventFolder,
    ...event,
    ...personFolder,
    ...person,
    ...personGartenFolder,
    ...personGarten,
    ...personGartenKulturFolder,
    ...personGartenKultur,
    ...personGartenKulturEventFolder,
    ...personGartenKulturEvent,
    ...personGartenKulturAnlieferungFolder,
    ...personGartenKulturAnlieferung,
    ...personGartenKulturAuslieferungFolder,
    ...personGartenKulturAuslieferung,
    ...personGartenKulturTeilkulturFolder,
    ...personGartenKulturTeilkultur,
    ...personGartenKulturZaehlungFolder,
    ...personGartenKulturZaehlung,
    ...personLieferungFolder,
    ...personLieferung,
    ...personSammlungFolder,
    ...personSammlungSammlung,
    ...sammelLieferungFolder,
    ...sammelLieferung,
    ...sammelLieferungLieferungFolder,
    ...sammelLieferungLieferung,
    ...sammlungFolder,
    ...teilkulturFolder,
    ...teilkultur,
    ...zaehlungFolder,
  ]

  /**
   * We ALWAYS add an array of nodes,
   * never a single one
   * not even for folders that are never more than one
   * because the function adding the nodes
   * should be able to pass none as well
   * for instance if a parent node is not open
   * or some filter is active
   */
  openNodes.forEach((url) => {
    if (!allParentNodesAreOpen(openNodes, url)) return

    if (url.length === 1 && url[0] === 'Zaehlungen') {
      nodes = [
        ...nodes,
        ...memoizeOne(() =>
          buildZaehlungZaehlung({
            nodes,
            store,
          }),
        )(),
      ]
    }
  })

  return nodes
}
